# Generated by Django 5.1.2 on 2025-11-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='SMA SLADOR', max_length=200)),
                ('school_address', models.TextField(default='Jl. Pendidikan No. 123, Jakarta')),
                ('school_phone', models.CharField(default='021-12345678', max_length=20)),
                ('school_email', models.EmailField(default='admin@smaslador.sch.id', max_length=254)),
                ('attendance_start_time', models.TimeField(default='07:00')),
                ('attendance_end_time', models.TimeField(default='15:00')),
                ('late_threshold', models.TimeField(default='07:15')),
                ('auto_absent_time', models.TimeField(default='08:00')),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_email_alerts', models.BooleanField(default=False)),
                ('enable_sms_alerts', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
