# Generated by Django 5.1.2 on 2025-11-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
