# Generated by Django 5.1.2 on 2025-10-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapel', models.CharField(max_length=120)),
                ('hari', models.CharField(max_length=15)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('ruang', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiswaKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_gabung', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
