# Generated by Django 5.1.2 on 2025-10-31 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='wali_guru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_wali', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_list', to='classes.kelas'),
        ),
        migrations.AddField(
            model_name='siswakelas',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='classes.kelas'),
        ),
        migrations.AddField(
            model_name='siswakelas',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keanggotaan_kelas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='siswakelas',
            unique_together={('siswa', 'kelas')},
        ),
    ]
