# Generated by Django 5.1.2 on 2025-11-05 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_kelas_tingkat_alter_kelas_kode_alter_kelas_wali_guru'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwal',
            options={'ordering': ['hari', 'jam_mulai'], 'verbose_name': 'Jadwal', 'verbose_name_plural': 'Jadwal'},
        ),
        migrations.AddField(
            model_name='jadwal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='hari',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat')], max_length=15),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='mapel',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(blank=True, limit_choices_to={'role': 'GURU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mata_pelajaran_diampu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Mata Pelajaran',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='jadwal',
            name='mata_pelajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_list', to='classes.matapelajaran'),
        ),
    ]
