# Generated by Django 5.1.2 on 2025-10-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(max_length=50)),
                ('entitas', models.CharField(max_length=50)),
                ('entitas_id', models.IntegerField()),
                ('payload_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_scan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('TERLAMBAT', 'Terlambat'), ('SAKIT', 'Sakit'), ('ALPHA', 'Alpha')], default='HADIR', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SesiPresensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('window_mulai', models.DateTimeField(blank=True, null=True)),
                ('window_selesai', models.DateTimeField(blank=True, null=True)),
                ('qr_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AKTIF', 'Aktif'), ('SELESAI', 'Selesai')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
