# Generated by Django 5.1.2 on 2025-10-31 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logaudit',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presensi',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_siswa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesipresensi',
            name='jadwal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesi_list', to='classes.jadwal'),
        ),
        migrations.AddField(
            model_name='sesipresensi',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_list', to='classes.kelas'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='sesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_list', to='attendance.sesipresensi'),
        ),
        migrations.AddIndex(
            model_name='presensi',
            index=models.Index(fields=['sesi'], name='attendance__sesi_id_6b07a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presensi',
            unique_together={('sesi', 'siswa')},
        ),
    ]
