# Generated by Django 5.1.2 on 2025-11-05 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('classes', '0004_alter_jadwal_options_jadwal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesipresensi',
            name='mata_pelajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesi_list', to='classes.matapelajaran'),
        ),
    ]
