# Generated by Django 5.1.2 on 2025-11-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_sesipresensi_mata_pelajaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='status',
            field=models.CharField(choices=[('HADIR', 'Hadir'), ('TERLAMBAT', 'Terlambat'), ('IZIN', 'Izin'), ('SAKIT', 'Sakit'), ('ALPHA', 'Alpha')], default='HADIR', max_length=10),
        ),
    ]
